// flow-typed signature: bc8a78310c599727a685c2fce2bdbeed
// flow-typed version: <<STUB>>/@tippyjs/react_v4.0.2/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tippyjs/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tippyjs/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tippyjs/react/dist/tippy-react.esm' {
  declare module.exports: any;
}

declare module '@tippyjs/react/dist/tippy-react.umd' {
  declare module.exports: any;
}

declare module '@tippyjs/react/dist/tippy-react.umd.min' {
  declare module.exports: any;
}

declare module '@tippyjs/react/headless/dist/tippy-react-headless.esm' {
  declare module.exports: any;
}

declare module '@tippyjs/react/headless/dist/tippy-react-headless.umd' {
  declare module.exports: any;
}

declare module '@tippyjs/react/headless/dist/tippy-react-headless.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tippyjs/react/dist/tippy-react.esm.js' {
  declare module.exports: $Exports<'@tippyjs/react/dist/tippy-react.esm'>;
}
declare module '@tippyjs/react/dist/tippy-react.umd.js' {
  declare module.exports: $Exports<'@tippyjs/react/dist/tippy-react.umd'>;
}
declare module '@tippyjs/react/dist/tippy-react.umd.min.js' {
  declare module.exports: $Exports<'@tippyjs/react/dist/tippy-react.umd.min'>;
}
declare module '@tippyjs/react/headless/dist/tippy-react-headless.esm.js' {
  declare module.exports: $Exports<'@tippyjs/react/headless/dist/tippy-react-headless.esm'>;
}
declare module '@tippyjs/react/headless/dist/tippy-react-headless.umd.js' {
  declare module.exports: $Exports<'@tippyjs/react/headless/dist/tippy-react-headless.umd'>;
}
declare module '@tippyjs/react/headless/dist/tippy-react-headless.umd.min.js' {
  declare module.exports: $Exports<'@tippyjs/react/headless/dist/tippy-react-headless.umd.min'>;
}
